name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"

      - name: Install Task
        run: |
          brew install go-task/tap/go-task

      - name: Build DMG
        run: task build-dmg

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/BrowserSchedule.dmg
          body: |
            ## BrowserSchedule ${{ github.ref_name }}

            Automatic browser switching based on time, day, and URL patterns.

            ### Installation
            1. Download `BrowserSchedule.dmg` from the [latest release](https://github.com/radiosilence/browser-schedule/releases/latest)
            2. Mount the DMG and drag BrowserSchedule.app to Applications
            3. Remove quarantine protection: `xattr -d com.apple.quarantine /Applications/BrowserSchedule.app`
            4. **Double-click the app** to set it as your default browser
            5. Configure via `~/.config/browser-schedule/config.toml`

            ### Changes
            See commit history for detailed changes.
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
